/*
 * generated by Xtext 2.10.0
 */
package kcl.ac.uk.xtext.ui.tests;

import com.google.inject.Injector;
import kcl.ac.uk.xtext.videoannotationsdsl.ui.internal.VideoannotationsdslActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class VideoAnnotationsDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return VideoannotationsdslActivator.getInstance().getInjector("kcl.ac.uk.xtext.VideoAnnotationsDSL");
	}

}
