/*
 * generated by Xtext 2.10.0
 */
package kcl.ac.uk.xtext.validation

import kcl.ac.uk.xtext.videoAnnotationsDSL.Annotation
import kcl.ac.uk.xtext.videoAnnotationsDSL.Move
import kcl.ac.uk.xtext.videoAnnotationsDSL.VideoAnnotationsDSLPackage
import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class VideoAnnotationsDSLValidator extends AbstractVideoAnnotationsDSLValidator {
	
	public static val INVALID_NAME = 'invalidName'
	public static val INVALID_MOVE = 'invalidMove'

    private static val char a = 'a'

	@Check
	def checkAnnotationStartsWithLetterA(Annotation annotation) {
		val char fstChar = annotation.name.charAt(0)
		if (fstChar != a) {
			warning('Name should start with letter \'a\' followed by a number', 
					VideoAnnotationsDSLPackage.Literals.ANNOTATION__NAME,
					INVALID_NAME)
		}
	}
}
