/*
 * generated by Xtext 2.10.0
 */
package kcl.ac.uk.xtext.parser.antlr;

import com.google.inject.Inject;
import kcl.ac.uk.xtext.parser.antlr.internal.InternalAnnotationsStoresParser;
import kcl.ac.uk.xtext.services.AnnotationsStoresGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class AnnotationsStoresParser extends AbstractAntlrParser {

	@Inject
	private AnnotationsStoresGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAnnotationsStoresParser createParser(XtextTokenStream stream) {
		return new InternalAnnotationsStoresParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "AnnotationStores";
	}

	public AnnotationsStoresGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AnnotationsStoresGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
