/*
 * generated by Xtext 2.10.0
 */
package kcl.ac.uk.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class VideoAnnotationsDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("kcl/ac/uk/xtext/parser/antlr/internal/InternalVideoAnnotationsDSL.tokens");
	}
}
