/*
 * generated by Xtext 2.10.0
 */
package kcl.ac.uk.xtext.ui.tests;

import com.google.inject.Injector;
import kcl.ac.uk.xtext.AnnotationsStores.ui.internal.AnnotationsStoresActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class AnnotationsStoresUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return AnnotationsStoresActivator.getInstance().getInjector("kcl.ac.uk.xtext.AnnotationsStores");
	}

}
