/*
 * generated by Xtext 2.10.0
 */
package kcl.ac.uk.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class VideoAnnotationsDSLStandaloneSetup extends VideoAnnotationsDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new VideoAnnotationsDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
