/*
 * generated by Xtext 2.10.0
 */
package kcl.ac.uk.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAnnotationsStoresScopeProvider extends DelegatingScopeProvider {
}
