/**
 * generated by Xtext 2.10.0
 */
package kcl.ac.uk.xtext.annotationsStores;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Annotation Stores</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link kcl.ac.uk.xtext.annotationsStores.AnnotationStores#getProposalElements <em>Proposal Elements</em>}</li>
 *   <li>{@link kcl.ac.uk.xtext.annotationsStores.AnnotationStores#getQuestionElements <em>Question Elements</em>}</li>
 *   <li>{@link kcl.ac.uk.xtext.annotationsStores.AnnotationStores#getChallengeElements <em>Challenge Elements</em>}</li>
 *   <li>{@link kcl.ac.uk.xtext.annotationsStores.AnnotationStores#getCommitmentElements <em>Commitment Elements</em>}</li>
 *   <li>{@link kcl.ac.uk.xtext.annotationsStores.AnnotationStores#getArgumentElements <em>Argument Elements</em>}</li>
 * </ul>
 *
 * @see kcl.ac.uk.xtext.annotationsStores.AnnotationsStoresPackage#getAnnotationStores()
 * @model
 * @generated
 */
public interface AnnotationStores extends EObject
{
  /**
   * Returns the value of the '<em><b>Proposal Elements</b></em>' containment reference list.
   * The list contents are of type {@link kcl.ac.uk.xtext.annotationsStores.ProposalStore}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Proposal Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Proposal Elements</em>' containment reference list.
   * @see kcl.ac.uk.xtext.annotationsStores.AnnotationsStoresPackage#getAnnotationStores_ProposalElements()
   * @model containment="true"
   * @generated
   */
  EList<ProposalStore> getProposalElements();

  /**
   * Returns the value of the '<em><b>Question Elements</b></em>' containment reference list.
   * The list contents are of type {@link kcl.ac.uk.xtext.annotationsStores.QuestionStore}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Question Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Question Elements</em>' containment reference list.
   * @see kcl.ac.uk.xtext.annotationsStores.AnnotationsStoresPackage#getAnnotationStores_QuestionElements()
   * @model containment="true"
   * @generated
   */
  EList<QuestionStore> getQuestionElements();

  /**
   * Returns the value of the '<em><b>Challenge Elements</b></em>' containment reference list.
   * The list contents are of type {@link kcl.ac.uk.xtext.annotationsStores.ChallengeStore}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Challenge Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Challenge Elements</em>' containment reference list.
   * @see kcl.ac.uk.xtext.annotationsStores.AnnotationsStoresPackage#getAnnotationStores_ChallengeElements()
   * @model containment="true"
   * @generated
   */
  EList<ChallengeStore> getChallengeElements();

  /**
   * Returns the value of the '<em><b>Commitment Elements</b></em>' containment reference list.
   * The list contents are of type {@link kcl.ac.uk.xtext.annotationsStores.CommitmentStore}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Commitment Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Commitment Elements</em>' containment reference list.
   * @see kcl.ac.uk.xtext.annotationsStores.AnnotationsStoresPackage#getAnnotationStores_CommitmentElements()
   * @model containment="true"
   * @generated
   */
  EList<CommitmentStore> getCommitmentElements();

  /**
   * Returns the value of the '<em><b>Argument Elements</b></em>' containment reference list.
   * The list contents are of type {@link kcl.ac.uk.xtext.annotationsStores.ArgumentStore}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Argument Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Argument Elements</em>' containment reference list.
   * @see kcl.ac.uk.xtext.annotationsStores.AnnotationsStoresPackage#getAnnotationStores_ArgumentElements()
   * @model containment="true"
   * @generated
   */
  EList<ArgumentStore> getArgumentElements();

} // AnnotationStores
