/**
 * generated by Xtext 2.10.0
 */
package kcl.ac.uk.xtext.annotationsStores;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Argument Store</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link kcl.ac.uk.xtext.annotationsStores.ArgumentStore#getName <em>Name</em>}</li>
 *   <li>{@link kcl.ac.uk.xtext.annotationsStores.ArgumentStore#getScope <em>Scope</em>}</li>
 *   <li>{@link kcl.ac.uk.xtext.annotationsStores.ArgumentStore#getFocus <em>Focus</em>}</li>
 *   <li>{@link kcl.ac.uk.xtext.annotationsStores.ArgumentStore#getContent <em>Content</em>}</li>
 *   <li>{@link kcl.ac.uk.xtext.annotationsStores.ArgumentStore#getTarget <em>Target</em>}</li>
 *   <li>{@link kcl.ac.uk.xtext.annotationsStores.ArgumentStore#getEffect <em>Effect</em>}</li>
 * </ul>
 *
 * @see kcl.ac.uk.xtext.annotationsStores.AnnotationsStoresPackage#getArgumentStore()
 * @model
 * @generated
 */
public interface ArgumentStore extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see kcl.ac.uk.xtext.annotationsStores.AnnotationsStoresPackage#getArgumentStore_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link kcl.ac.uk.xtext.annotationsStores.ArgumentStore#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Scope</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Scope</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scope</em>' containment reference.
   * @see #setScope(Scope)
   * @see kcl.ac.uk.xtext.annotationsStores.AnnotationsStoresPackage#getArgumentStore_Scope()
   * @model containment="true"
   * @generated
   */
  Scope getScope();

  /**
   * Sets the value of the '{@link kcl.ac.uk.xtext.annotationsStores.ArgumentStore#getScope <em>Scope</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Scope</em>' containment reference.
   * @see #getScope()
   * @generated
   */
  void setScope(Scope value);

  /**
   * Returns the value of the '<em><b>Focus</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Focus</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Focus</em>' containment reference.
   * @see #setFocus(Focus)
   * @see kcl.ac.uk.xtext.annotationsStores.AnnotationsStoresPackage#getArgumentStore_Focus()
   * @model containment="true"
   * @generated
   */
  Focus getFocus();

  /**
   * Sets the value of the '{@link kcl.ac.uk.xtext.annotationsStores.ArgumentStore#getFocus <em>Focus</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Focus</em>' containment reference.
   * @see #getFocus()
   * @generated
   */
  void setFocus(Focus value);

  /**
   * Returns the value of the '<em><b>Content</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Content</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Content</em>' attribute.
   * @see #setContent(String)
   * @see kcl.ac.uk.xtext.annotationsStores.AnnotationsStoresPackage#getArgumentStore_Content()
   * @model
   * @generated
   */
  String getContent();

  /**
   * Sets the value of the '{@link kcl.ac.uk.xtext.annotationsStores.ArgumentStore#getContent <em>Content</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Content</em>' attribute.
   * @see #getContent()
   * @generated
   */
  void setContent(String value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Target</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' attribute.
   * @see #setTarget(String)
   * @see kcl.ac.uk.xtext.annotationsStores.AnnotationsStoresPackage#getArgumentStore_Target()
   * @model
   * @generated
   */
  String getTarget();

  /**
   * Sets the value of the '{@link kcl.ac.uk.xtext.annotationsStores.ArgumentStore#getTarget <em>Target</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' attribute.
   * @see #getTarget()
   * @generated
   */
  void setTarget(String value);

  /**
   * Returns the value of the '<em><b>Effect</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Effect</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Effect</em>' containment reference.
   * @see #setEffect(Effect)
   * @see kcl.ac.uk.xtext.annotationsStores.AnnotationsStoresPackage#getArgumentStore_Effect()
   * @model containment="true"
   * @generated
   */
  Effect getEffect();

  /**
   * Sets the value of the '{@link kcl.ac.uk.xtext.annotationsStores.ArgumentStore#getEffect <em>Effect</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Effect</em>' containment reference.
   * @see #getEffect()
   * @generated
   */
  void setEffect(Effect value);

} // ArgumentStore
