/**
 * generated by Xtext 2.10.0
 */
package kcl.ac.uk.xtext.annotationsStores;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Challenge Store</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link kcl.ac.uk.xtext.annotationsStores.ChallengeStore#getName <em>Name</em>}</li>
 *   <li>{@link kcl.ac.uk.xtext.annotationsStores.ChallengeStore#getSender <em>Sender</em>}</li>
 *   <li>{@link kcl.ac.uk.xtext.annotationsStores.ChallengeStore#getTarget <em>Target</em>}</li>
 *   <li>{@link kcl.ac.uk.xtext.annotationsStores.ChallengeStore#getEffect <em>Effect</em>}</li>
 * </ul>
 *
 * @see kcl.ac.uk.xtext.annotationsStores.AnnotationsStoresPackage#getChallengeStore()
 * @model
 * @generated
 */
public interface ChallengeStore extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see kcl.ac.uk.xtext.annotationsStores.AnnotationsStoresPackage#getChallengeStore_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link kcl.ac.uk.xtext.annotationsStores.ChallengeStore#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Sender</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sender</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sender</em>' attribute.
   * @see #setSender(String)
   * @see kcl.ac.uk.xtext.annotationsStores.AnnotationsStoresPackage#getChallengeStore_Sender()
   * @model
   * @generated
   */
  String getSender();

  /**
   * Sets the value of the '{@link kcl.ac.uk.xtext.annotationsStores.ChallengeStore#getSender <em>Sender</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sender</em>' attribute.
   * @see #getSender()
   * @generated
   */
  void setSender(String value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Target</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' attribute.
   * @see #setTarget(String)
   * @see kcl.ac.uk.xtext.annotationsStores.AnnotationsStoresPackage#getChallengeStore_Target()
   * @model
   * @generated
   */
  String getTarget();

  /**
   * Sets the value of the '{@link kcl.ac.uk.xtext.annotationsStores.ChallengeStore#getTarget <em>Target</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' attribute.
   * @see #getTarget()
   * @generated
   */
  void setTarget(String value);

  /**
   * Returns the value of the '<em><b>Effect</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Effect</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Effect</em>' containment reference.
   * @see #setEffect(Effect)
   * @see kcl.ac.uk.xtext.annotationsStores.AnnotationsStoresPackage#getChallengeStore_Effect()
   * @model containment="true"
   * @generated
   */
  Effect getEffect();

  /**
   * Sets the value of the '{@link kcl.ac.uk.xtext.annotationsStores.ChallengeStore#getEffect <em>Effect</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Effect</em>' containment reference.
   * @see #getEffect()
   * @generated
   */
  void setEffect(Effect value);

} // ChallengeStore
