/**
 * generated by Xtext 2.10.0
 */
package kcl.ac.uk.xtext.annotationsStores;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Focus</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link kcl.ac.uk.xtext.annotationsStores.Focus#getFocus <em>Focus</em>}</li>
 * </ul>
 *
 * @see kcl.ac.uk.xtext.annotationsStores.AnnotationsStoresPackage#getFocus()
 * @model
 * @generated
 */
public interface Focus extends EObject
{
  /**
   * Returns the value of the '<em><b>Focus</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Focus</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Focus</em>' attribute.
   * @see #setFocus(String)
   * @see kcl.ac.uk.xtext.annotationsStores.AnnotationsStoresPackage#getFocus_Focus()
   * @model
   * @generated
   */
  String getFocus();

  /**
   * Sets the value of the '{@link kcl.ac.uk.xtext.annotationsStores.Focus#getFocus <em>Focus</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Focus</em>' attribute.
   * @see #getFocus()
   * @generated
   */
  void setFocus(String value);

} // Focus
