/**
 * generated by Xtext 2.10.0
 */
package kcl.ac.uk.xtext.annotationsStores.impl;

import kcl.ac.uk.xtext.annotationsStores.AnnotationStores;
import kcl.ac.uk.xtext.annotationsStores.AnnotationsStoresFactory;
import kcl.ac.uk.xtext.annotationsStores.AnnotationsStoresPackage;
import kcl.ac.uk.xtext.annotationsStores.ArgumentStore;
import kcl.ac.uk.xtext.annotationsStores.ChallengeStore;
import kcl.ac.uk.xtext.annotationsStores.CommitmentStore;
import kcl.ac.uk.xtext.annotationsStores.Focus;
import kcl.ac.uk.xtext.annotationsStores.ProposalStore;
import kcl.ac.uk.xtext.annotationsStores.QuestionStore;
import kcl.ac.uk.xtext.annotationsStores.Scope;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class AnnotationsStoresPackageImpl extends EPackageImpl implements AnnotationsStoresPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass annotationStoresEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass proposalStoreEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass questionStoreEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass challengeStoreEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass commitmentStoreEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass argumentStoreEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass scopeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass focusEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see kcl.ac.uk.xtext.annotationsStores.AnnotationsStoresPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private AnnotationsStoresPackageImpl()
  {
    super(eNS_URI, AnnotationsStoresFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   * 
   * <p>This method is used to initialize {@link AnnotationsStoresPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static AnnotationsStoresPackage init()
  {
    if (isInited) return (AnnotationsStoresPackage)EPackage.Registry.INSTANCE.getEPackage(AnnotationsStoresPackage.eNS_URI);

    // Obtain or create and register package
    AnnotationsStoresPackageImpl theAnnotationsStoresPackage = (AnnotationsStoresPackageImpl)(EPackage.Registry.INSTANCE.get(eNS_URI) instanceof AnnotationsStoresPackageImpl ? EPackage.Registry.INSTANCE.get(eNS_URI) : new AnnotationsStoresPackageImpl());

    isInited = true;

    // Create package meta-data objects
    theAnnotationsStoresPackage.createPackageContents();

    // Initialize created meta-data
    theAnnotationsStoresPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theAnnotationsStoresPackage.freeze();

  
    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(AnnotationsStoresPackage.eNS_URI, theAnnotationsStoresPackage);
    return theAnnotationsStoresPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getAnnotationStores()
  {
    return annotationStoresEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAnnotationStores_ProposalElements()
  {
    return (EReference)annotationStoresEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAnnotationStores_QuestionElements()
  {
    return (EReference)annotationStoresEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAnnotationStores_ChallengeElements()
  {
    return (EReference)annotationStoresEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAnnotationStores_CommitmentElements()
  {
    return (EReference)annotationStoresEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAnnotationStores_ArgumentElements()
  {
    return (EReference)annotationStoresEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getProposalStore()
  {
    return proposalStoreEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getProposalStore_Name()
  {
    return (EAttribute)proposalStoreEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getProposalStore_Scope()
  {
    return (EReference)proposalStoreEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getProposalStore_Focus()
  {
    return (EReference)proposalStoreEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getProposalStore_Content()
  {
    return (EAttribute)proposalStoreEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getQuestionStore()
  {
    return questionStoreEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getQuestionStore_Name()
  {
    return (EAttribute)questionStoreEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getQuestionStore_Sender()
  {
    return (EAttribute)questionStoreEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getQuestionStore_Scope()
  {
    return (EReference)questionStoreEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getQuestionStore_Focus()
  {
    return (EReference)questionStoreEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getQuestionStore_Content()
  {
    return (EAttribute)questionStoreEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getChallengeStore()
  {
    return challengeStoreEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getChallengeStore_Name()
  {
    return (EAttribute)challengeStoreEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getChallengeStore_Sender()
  {
    return (EAttribute)challengeStoreEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getChallengeStore_Target()
  {
    return (EAttribute)challengeStoreEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getCommitmentStore()
  {
    return commitmentStoreEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getCommitmentStore_Name()
  {
    return (EAttribute)commitmentStoreEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getCommitmentStore_Scope()
  {
    return (EReference)commitmentStoreEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getCommitmentStore_Focus()
  {
    return (EReference)commitmentStoreEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getCommitmentStore_Content()
  {
    return (EAttribute)commitmentStoreEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getArgumentStore()
  {
    return argumentStoreEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getArgumentStore_Name()
  {
    return (EAttribute)argumentStoreEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getArgumentStore_Scope()
  {
    return (EReference)argumentStoreEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getArgumentStore_Focus()
  {
    return (EReference)argumentStoreEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getArgumentStore_Content()
  {
    return (EAttribute)argumentStoreEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getArgumentStore_Target()
  {
    return (EAttribute)argumentStoreEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getScope()
  {
    return scopeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getScope_Scope()
  {
    return (EAttribute)scopeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getFocus()
  {
    return focusEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getFocus_Focus()
  {
    return (EAttribute)focusEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AnnotationsStoresFactory getAnnotationsStoresFactory()
  {
    return (AnnotationsStoresFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    annotationStoresEClass = createEClass(ANNOTATION_STORES);
    createEReference(annotationStoresEClass, ANNOTATION_STORES__PROPOSAL_ELEMENTS);
    createEReference(annotationStoresEClass, ANNOTATION_STORES__QUESTION_ELEMENTS);
    createEReference(annotationStoresEClass, ANNOTATION_STORES__CHALLENGE_ELEMENTS);
    createEReference(annotationStoresEClass, ANNOTATION_STORES__COMMITMENT_ELEMENTS);
    createEReference(annotationStoresEClass, ANNOTATION_STORES__ARGUMENT_ELEMENTS);

    proposalStoreEClass = createEClass(PROPOSAL_STORE);
    createEAttribute(proposalStoreEClass, PROPOSAL_STORE__NAME);
    createEReference(proposalStoreEClass, PROPOSAL_STORE__SCOPE);
    createEReference(proposalStoreEClass, PROPOSAL_STORE__FOCUS);
    createEAttribute(proposalStoreEClass, PROPOSAL_STORE__CONTENT);

    questionStoreEClass = createEClass(QUESTION_STORE);
    createEAttribute(questionStoreEClass, QUESTION_STORE__NAME);
    createEAttribute(questionStoreEClass, QUESTION_STORE__SENDER);
    createEReference(questionStoreEClass, QUESTION_STORE__SCOPE);
    createEReference(questionStoreEClass, QUESTION_STORE__FOCUS);
    createEAttribute(questionStoreEClass, QUESTION_STORE__CONTENT);

    challengeStoreEClass = createEClass(CHALLENGE_STORE);
    createEAttribute(challengeStoreEClass, CHALLENGE_STORE__NAME);
    createEAttribute(challengeStoreEClass, CHALLENGE_STORE__SENDER);
    createEAttribute(challengeStoreEClass, CHALLENGE_STORE__TARGET);

    commitmentStoreEClass = createEClass(COMMITMENT_STORE);
    createEAttribute(commitmentStoreEClass, COMMITMENT_STORE__NAME);
    createEReference(commitmentStoreEClass, COMMITMENT_STORE__SCOPE);
    createEReference(commitmentStoreEClass, COMMITMENT_STORE__FOCUS);
    createEAttribute(commitmentStoreEClass, COMMITMENT_STORE__CONTENT);

    argumentStoreEClass = createEClass(ARGUMENT_STORE);
    createEAttribute(argumentStoreEClass, ARGUMENT_STORE__NAME);
    createEReference(argumentStoreEClass, ARGUMENT_STORE__SCOPE);
    createEReference(argumentStoreEClass, ARGUMENT_STORE__FOCUS);
    createEAttribute(argumentStoreEClass, ARGUMENT_STORE__CONTENT);
    createEAttribute(argumentStoreEClass, ARGUMENT_STORE__TARGET);

    scopeEClass = createEClass(SCOPE);
    createEAttribute(scopeEClass, SCOPE__SCOPE);

    focusEClass = createEClass(FOCUS);
    createEAttribute(focusEClass, FOCUS__FOCUS);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes

    // Initialize classes and features; add operations and parameters
    initEClass(annotationStoresEClass, AnnotationStores.class, "AnnotationStores", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getAnnotationStores_ProposalElements(), this.getProposalStore(), null, "proposalElements", null, 0, -1, AnnotationStores.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAnnotationStores_QuestionElements(), this.getQuestionStore(), null, "questionElements", null, 0, -1, AnnotationStores.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAnnotationStores_ChallengeElements(), this.getChallengeStore(), null, "challengeElements", null, 0, -1, AnnotationStores.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAnnotationStores_CommitmentElements(), this.getCommitmentStore(), null, "commitmentElements", null, 0, -1, AnnotationStores.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAnnotationStores_ArgumentElements(), this.getArgumentStore(), null, "argumentElements", null, 0, -1, AnnotationStores.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(proposalStoreEClass, ProposalStore.class, "ProposalStore", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getProposalStore_Name(), ecorePackage.getEString(), "name", null, 0, 1, ProposalStore.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getProposalStore_Scope(), this.getScope(), null, "scope", null, 0, 1, ProposalStore.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getProposalStore_Focus(), this.getFocus(), null, "focus", null, 0, 1, ProposalStore.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getProposalStore_Content(), ecorePackage.getEString(), "content", null, 0, 1, ProposalStore.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(questionStoreEClass, QuestionStore.class, "QuestionStore", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getQuestionStore_Name(), ecorePackage.getEString(), "name", null, 0, 1, QuestionStore.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getQuestionStore_Sender(), ecorePackage.getEString(), "sender", null, 0, 1, QuestionStore.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getQuestionStore_Scope(), this.getScope(), null, "scope", null, 0, 1, QuestionStore.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getQuestionStore_Focus(), this.getFocus(), null, "focus", null, 0, 1, QuestionStore.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getQuestionStore_Content(), ecorePackage.getEString(), "content", null, 0, 1, QuestionStore.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(challengeStoreEClass, ChallengeStore.class, "ChallengeStore", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getChallengeStore_Name(), ecorePackage.getEString(), "name", null, 0, 1, ChallengeStore.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getChallengeStore_Sender(), ecorePackage.getEString(), "sender", null, 0, 1, ChallengeStore.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getChallengeStore_Target(), ecorePackage.getEString(), "target", null, 0, 1, ChallengeStore.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(commitmentStoreEClass, CommitmentStore.class, "CommitmentStore", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCommitmentStore_Name(), ecorePackage.getEString(), "name", null, 0, 1, CommitmentStore.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCommitmentStore_Scope(), this.getScope(), null, "scope", null, 0, 1, CommitmentStore.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCommitmentStore_Focus(), this.getFocus(), null, "focus", null, 0, 1, CommitmentStore.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getCommitmentStore_Content(), ecorePackage.getEString(), "content", null, 0, 1, CommitmentStore.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(argumentStoreEClass, ArgumentStore.class, "ArgumentStore", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getArgumentStore_Name(), ecorePackage.getEString(), "name", null, 0, 1, ArgumentStore.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getArgumentStore_Scope(), this.getScope(), null, "scope", null, 0, 1, ArgumentStore.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getArgumentStore_Focus(), this.getFocus(), null, "focus", null, 0, 1, ArgumentStore.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getArgumentStore_Content(), ecorePackage.getEString(), "content", null, 0, 1, ArgumentStore.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getArgumentStore_Target(), ecorePackage.getEString(), "target", null, 0, 1, ArgumentStore.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(scopeEClass, Scope.class, "Scope", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getScope_Scope(), ecorePackage.getEString(), "scope", null, 0, 1, Scope.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(focusEClass, Focus.class, "Focus", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getFocus_Focus(), ecorePackage.getEString(), "focus", null, 0, 1, Focus.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //AnnotationsStoresPackageImpl
